{
 "title": "4D",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(FourD_Status_Process_total {job=\"FourD\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "FourD_GetMemoryStatistics_bytes{instance=\"$instance\"}",
     "legendFormat": "{{memory}}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "User" }
   ],
   "targets": [
    {
     "expr": "FourD_Status_Clients_total{instance=\"$instance\"}",
     "legendFormat": "User"
    },
    {
     "expr": "FourD_Status_Process_total{instance=\"$instance\"}",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "DB Measures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "FourD_Measures_DB_bytes{instance=\"$instance\"}",
     "legendFormat": "{{DB}}"
    }
   ]
  },
  {
   "title": "Scrap time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "FourD_scrape_duration_milliseconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Table data read bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "FourD_Measures_ReadDisk_bytes{instance=\"$instance\", type=\"data\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Table index read bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "FourD_Measures_ReadDisk_bytes{instance=\"$instance\", type=\"index\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Table data write bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "FourD_Measures_WriteDisk_bytes{instance=\"$instance\", type=\"data\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Table indexwrite bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "FourD_Measures_WriteDisk_bytes{instance=\"$instance\", type=\"index\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Table data Cache Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "FourD_Measures_ReadCache_bytes{type=\"data\",instance=\"$instance\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Table index Cache Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "FourD_Measures_ReadCache_bytes{instance=\"$instance\",type=\"index\"}",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Queries Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "FourD_Measures_Queries_milliseconds{instance=\"$instance\"}",
     "legendFormat": "{{statement}}"
    }
   ]
  },
  {
   "title": "Queries count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "FourD_Measures_Queries_total{instance=\"$instance\"}",
     "legendFormat": "{{statement}}"
    }
   ]
  }
 ]
}